### PR TITLE
Made extension virtualenv aware

### PR DESCRIPTION
**Pull request by rob-a-bolton**
Made extension virtualenv aware by exporting VIRTUAL_ENV when bin/python detected from project root, fixing #37

### CODE REVIEW

**Comment by lgeiger** [comment]
@rob-a-bolton Would you be interested in helping us maintain `ide-python`? I'd be very happy to add you as a collaborator to the repo.

**Comment by rob-a-bolton** [comment]
No problem, thanks for the package - it's very useful. I'd certainly be up for helping to maintain ide-python.

**Comment by lgeiger** [comment]
Cool, I'll add you to the repo 🎉

**Comment by franklinyu** [comment]
Doesn't seem to work on Windows? I'm using `venv` from Python 3.

**Pull request merged**
