### PR TITLE
Get environment variable w/o killing CPU on linux

### LINKED ISSUE #20: ide-python starts rogue bash process
Whenever I start atom (or whenever I enable ide-python in settings), there's a bash process that gets spawned. It clogs the CPU and it cannot be ended with SIGTERM, only SIGKILL.

The command, as shown in `ps` is `/bin/bash -ilc env; exit`

Other info:

```
$uname -a
Linux kramer-VirtualBox 4.10.0-35-generic #39-Ubuntu SMP Wed Sep 13 07:46:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$atom --version
Atom    : 1.20.1
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

### PR DESCRIPTION
**Pull request by kbrose**
This is an attempt to fix #20.

I do not have access to a Mac, so I cannot check verify that this change does't re-introduce #4.

### CODE REVIEW

**Comment by lgeiger** [comment]
@kbrose Thanks a lot for your PR! 👍 

Unfortunately this re-introduces #4 since `atom.getLoadSettings().env` doesn't correctly get the `PATH` on mac. As soon as I find time I'll test this again and see if it's a bug in Atom core or if we can find a better solution that works on linux too.

**Comment by lgeiger** [comment]
@kbrose Thanks a lot for your PR! 👍 

Unfortunately this re-introduces #4 since `atom.getLoadSettings().env` doesn't correctly get the `PATH` on mac. As soon as I find time I'll test this again and see if it's a bug in Atom core or if we can find a better solution that works on linux too.

**Comment by kbrose** [comment]
It doesn't? Do you have a pointer to a discussion about that?

**Comment by kbrose** [comment]
What about `atom.updateProcessEnv` and `process.env`?

**Comment by lgeiger** [comment]
> What about atom.updateProcessEnv and process.env?

Thanks for the suggestions, unfortunately both don't help either 😕 
Looks like we're running into an Atom bug here.

Could you test if #29 works for you?

**Pull request closed without merging**
