### PR TITLE
accept flake8 as a config source, rather than pyflakes

### LINKED ISSUE #80: support 'flake8' as a pyls Plugins Configuration Source
pyls appears to support flake8 as a configuration source. It may well be the case that adding 'flake8' to the set of allowed strings might be sufficient to get this going?

### PR DESCRIPTION
**Pull request by ediphy-azorab**
fixes #80

### CODE REVIEW

**Comment by ediphy-azorab** [comment]
upon further testing, I now suspect this might have been picking up a stray pycodestyle config...

**Comment by ediphy-azorab** [comment]
So it turns out that the configuration sources are, in fact, in a different section of the config. This is now working for me with either pycodestyle or flake8 configs

**Comment by lgeiger** [comment]
@ediphy-azorab Are you interested in helping us maintain `ide-python`?  I'm happy to invite you to the repo.

**Comment by maxim-lian** [comment]
This would be awesome and mean I can move over from `flake8-lint`. But how would this work? I had thought that `flake8` wasn't yet supported by pyls - it's not on their [readme](https://github.com/palantir/python-language-server), and I coincidentally asked a [question](https://github.com/palantir/python-language-server/issues/259#issuecomment-365488655) on their readme yday. 

Sounds like I'm mistaken though?

**Comment by maxim-lian** [comment]
...or this is just the config source, rather than actually running `flake8`?

**Comment by lgeiger** [comment]
> ...or this is just the config source, rather than actually running flake8?

Yep, but it should result in the same linting behaviour. Checkout https://github.com/lgeiger/ide-python#configuration

**Comment by maxim-lian** [comment]
Thanks @lgeiger 

This mostly works well. It doesn't do `isort`, because that's at flake8 plugin, and so covering the three `flake8` libraries in this instance doesn't quite get there.

But that's an upstream issue. (and fwiw there is an isort plugin which sorts, but it doesn't lint)

**Comment by lgeiger** [comment]
Yes, there is no isort plugin for pyls which can be installed separately

**Comment by ediphy-azorab** [comment]
@lgeiger I've got somewhat limited bandwidth, but I'm certainly happy to help out

**Comment by lgeiger** [comment]
> I've got somewhat limited bandwidth, but I'm certainly happy to help out

🆒

**Comment by maxim-lian** [comment]
> Yes, there is an isort plugin for pyls which can be installed separately

> and fwiw there is an isort plugin which sorts, but it doesn't lint

**Pull request merged**
